name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build

    runs-on: macos-13

    env:
      XCODE_VERSION_PATH: /Applications/Xcode_15.0.1.app  # See available versions & paths: https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode

    defaults:
      run:
        shell: bash

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode version
        run: sudo xcode-select -s ${{ env.XCODE_VERSION_PATH }}

      - name: Execute build script
        run: ./scripts/build.sh
